version: '3.3'
services:
    mysql:
        image: 'mysql/mysql-server:8.0'
        restart: always
        ports:
            - '3306:3306'
        expose:
            - 3306
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './dbData:/var/lib/mysql'
